### ISSUE TITLE
pass-tomb assumes $USER as the user's group

### ISSUE THREAD

**Issue by tsuflux** [roddhjav/pass-tomb#1]
If the user's group name differs from the user's account name, pass-tomb will fail to set the permissions of the decrypted password store. See chown invocation [1](https://github.com/roddhjav/pass-tomb/blob/3d82f4611bdf6a59bf5d31f1e7207134f4eea50b/tomb.bash#L148) and [2](https://github.com/roddhjav/pass-tomb/blob/3d82f4611bdf6a59bf5d31f1e7207134f4eea50b/tomb.bash#L215).

**Comment by roddhjav** [comment]
Thanks for the feedback,

This `chown` invocation was needed for older version of tomb, it should not be mandatory anymore.

Does remove the `chown` invocation solve the issue?

**Comment by tsuflux** [comment]
Thank you for your quick answer.

No, removing `chown` leaves the volume owned by `root:root` and thus unusable as a normal user.

I am using the AUR package and therefore `tomb-git` but manually creating a new tomb has the permissions set to `root:root` as well.

**Comment by roddhjav** [comment]
Yes, this is because when using creating a normal tomb, it is the user job to set the rights. You can see the discussion on the issue [here](https://github.com/dyne/Tomb/commit/843b7fdfc4c125065d31cc11cff8a994ed680bd4).

It should be fixed now.
