### ISSUE TITLE
Cannot create tomb on OS X.

### ISSUE THREAD

**Issue by tylerjw** [roddhjav/pass-tomb#11]
I was able to get it to build and install by making minor modifications to the make file:

```diff
$ git diff
diff --git a/Makefile b/Makefile
index 9674cd3..26d7b13 100644
--- a/Makefile
+++ b/Makefile
@@ -16,9 +16,9 @@ all:
 install:
        @install -v -d "$(DESTDIR)$(MANDIR)/man1" && install -m 0644 -v pass-$(PROG).1 "$(DESTDIR)$(MANDIR)/man1/pass-$(PROG).1"
        @install -v -d "$(DESTDIR)$(SYSTEM_EXTENSION_DIR)/"
-       @install -Dm0755 $(PROG).bash "$(DESTDIR)$(SYSTEM_EXTENSION_DIR)/$(PROG).bash"
-       @install -Dm0755 open.bash "$(DESTDIR)$(SYSTEM_EXTENSION_DIR)/open.bash"
-       @install -Dm0755 close.bash "$(DESTDIR)$(SYSTEM_EXTENSION_DIR)/close.bash"
+       @install -m 0755 $(PROG).bash "$(DESTDIR)$(SYSTEM_EXTENSION_DIR)/$(PROG).bash"
+       @install -m 0755 open.bash "$(DESTDIR)$(SYSTEM_EXTENSION_DIR)/open.bash"
+       @install -m 0755 close.bash "$(DESTDIR)$(SYSTEM_EXTENSION_DIR)/close.bash"
        @echo
        @echo "pass-$(PROG) is installed succesfully"
        @echo
```

And installing like this:
```bash
$sudo make install PREFIX=/usr/local
```

When I try to create a new tomb this is the output:

```bash
$ pass tomb
 \e[1;31m[x]\e[0m \e[1mError :\e[0m Tomb is not present.
```

I read issue #4 and I believe this issue is because it is trying to open `pinentry-curses`, however on OS X the pin entry program is called `pinentry-mac`.  Here is the line from my `gpg-agent.conf`:

```
pinentry-program /usr/local/MacGPG2/libexec/pinentry-mac.app/Contents/MacOS/pinentry-mac
```

Is there a way I could configure pass-tomb to use this pin entry program or help debug this in any way.  I would really like to use pass-tomb on my mac and it seems like it should work without much of a change.  Thank you.

**Comment by roddhjav** [comment]
First thank a lot for these feedback regarding installation and execution on MAC, because I don't have a MAC myself, I cannot test it. (although I think Travis now support mac OS VM)

Regarding your issue, it is because `pass-tomb` requires `tomb` as dependency . And `tomb` does not work on Mac OS X, because Tomb is based on dm-crypt.

**Comment by tylerjw** [comment]
Ah, thank you, you can close this then.  I think I might try writing a plugin that just uses tar and gpg to do something similar.

**Comment by roddhjav** [comment]
Keep in touch, Tomb might in the future support other encryption system (like VeraCrypt).
