### ISSUE TITLE
pass open fails unless swapoff -a is run

### ISSUE THREAD

**Issue by thewaywest** [roddhjav/pass-tomb#12]
MEta
> Ubuntu 16.04.01 / elementary os loki, encrypted volume, swap shared w multiple OS (?)
> pass-tomb (latest)
> Tomb 2.4

Latest version of tomb fails when pass-tomb tries to open the store when a swap file is present and in use:
> ~$ pass open 
> [x] Error : Unable to open the password tomb.
> ~$ tomb open .password.tomb -k .password.tomb.key                                                        
> > tomb  .  Commanded to open tomb .password.tomb
> > tomb  .  An active swap partition is detected...
> > tomb [W] This poses a security risk.
> > tomb [W] You can deactivate all swap partitions using the command:
> > tomb [W]  swapoff -a
> > tomb [W] [#163] I may not detect plain swaps on an encrypted volume.
> > tomb [W] But if you want to proceed like this, use the -f (force) flag.
> > tomb [E] Operation aborted.

> ~$
> ~$ sudo swapoff -a
> ~$ pass open
> > You need a passphrase to unlock the secret key for
> > user: "XXXXXXXXXX <xxxxx@xxxxxxx.com>"
> > 2048-bit RSA key, ID 5FCC6403, created 2017-11-10 (main key ID DA795D2A)
> > 
> >  (*) Your password tomb has been opened in /home/mark/.password-store/.
> >   .  You can now use pass as usual.
> >   .  When finished, close the password tomb using 'pass close'.

> ~$

I don't remember if I encrypted my swap, but as this dev machine has Windows and Linux running in parallel, I probably tried to share it, and left it unencrypted.

Could you add a -F option to `pass open --force (or -F)' that turns swap off prior to opening, and back on at the end of the bash script? Running with swap off is deadly...

**Comment by roddhjav** [comment]
This is actually a `feature not a bug` (TM). If your swap is not encrypted, Tomb (and therefore pass-tomb) won't open/create the tomb for security reason. The solutions are:
* Encrypt your swap and you'll never have an issue.
* Disable the swap (with swapoff).
* Force Tomb to ignore the swap stage.

The first two solutions do not depend of pass-tomb. I don't think pass-tomb should take itself the right to disable the swap for the whole system. It could lead to unexpected side effects.

However, I can add a `-f/--force` option to force the operations  even if the swap is active.

**Comment by roddhjav** [comment]
Should be fixed in `pass-tomb 1.1`

**Comment by thewaywest** [comment]
Thank you. Note that the swap needs to be disabled only while the tomb is being opened. I created a bash script that runs a sudo swapoff -a, then pass open, then sudo swapon -a, reducing any performance hit due to lack of an active swap.
