### ISSUE TITLE
[x] Error : You set an invalid GPG ID.

### ISSUE THREAD

**Issue by vtbhujlt** [roddhjav/pass-tomb#15]
Hi ! It happened when I did 
`pass tomb mymail@mail.com`
or even with my key ID in LONG or SHORT format... I only have the warning
`  w  mymail@mail.com is not a valid key ID.`
before the error, even with debug and verbose options. I don't know what to give as details... Running on voidlinux, I have an alias for gpg in my bash_aliases file:
`alias gpg=gpg2`
pass tomb was installed from the git repo.

**Comment by roddhjav** [comment]
Hi, Can you provide more information on your issue like:
* Your `gpg`, `tomb` and `pass-tomb` version.
* The output of `gpg -K mymail@mail.com` to be sure you own the key.

**Comment by vtbhujlt** [comment]
Okay, I'm so sorry, my bad, I forgot to verify which version of gpg tomb is using. My key was created with gpg -v 2.x.x and tomb is using gpg -v 1.x.x, but both of gpg versions are installed in my system and gpg -v 1.x.x doesn't see keys of gpg -v 2.x.x. And tomb is searching for /usr/bin/gpg so it doesn't read my alias. 

i've just linked /usr/bin/gpg2 to /usr/bin/gpg but there is another better way to do than this solution or rewriting tomb to use gpg2 (that will not be easy at all for me I imagine) ?
