### ISSUE TITLE
Close does not like filenames with extensions

### ISSUE THREAD

**Issue by tsuflux** [roddhjav/pass-tomb#2]
I have set `PASSWORD_STORE_TOMB_FILE="$HOME/password.tomb"`.

With this setting `pass close` calls `tomb close` with the argument `password.tomb`, see [here](https://github.com/roddhjav/pass-tomb/blob/2fa052fbd8c964783b786776d34e565d0887c9af/tomb.bash#L173). However, `tomb list` shows that the opened tomb is instead just called `password`. Thus pass-tomb will fail to close the password tomb.

**Comment by roddhjav** [comment]
`TOMB_NAME=${TOMB_FILE##*/}` only retrieve the base name of the tomb file. I added the extension detection. In order to keep the track of this in the future, I also changed the tomb name in the tests.

Thanks again for the feedback!
