### ISSUE TITLE
pass-tomb creates multiple systemd timers

### ISSUE THREAD

**Issue by ghost** [roddhjav/pass-tomb#24]
Let's say I set the timer to 1h when creating the tomb. If I manually close the tomb after 20min and then reopen the tomb 5min later, another timer is created while the previous timer is also present. Shouldn't the previous timer be updated rather than creating a new timer every time pass is closed and opened?

**Comment by roddhjav** [comment]
Your are right, I need to improve this. I will do it. Just allow a bit of time (otherwise PR are welcome).
