### ISSUE TITLE
After Fedora upgrade to 30, pass tomb is timing out. 

### ISSUE THREAD

**Issue by saneax** [roddhjav/pass-tomb#26]
I do not get a prompt for the key passphrase and hence the script times out after some time - 

pass open --verbose
  .  pass Opening the password tomb /home/sanjxxxx.password.tomb using the key /home/sanjxxxx/.password.tomb.key
  .  tomb  .  Commanded to open tomb /home/sanjxxxx/.password.tomb
  .  tomb  .  An active swap partition is detected...
  .  tomb (*) The undertaker found that all swap partitions are encrypted. Good.
  .  tomb [W] File is not yet a tomb: /home/sanjxxxx/.password.tomb
  .  tomb  .  Valid tomb file found: /home/sanjxxxx/.password.tomb
  .  tomb  .  Key is valid.
  .  tomb (*) Opening .password on /home/sanjxxxx/.password-store/
  .  tomb  .  This tomb is a valid LUKS encrypted device.
  .  tomb  .  Cipher is "aes" mode "xts-plain64:sha256" hash "sha256"
  .  tomb [E] No valid password supplied.
 [x] Error: Unable to open the password tomb.

**Comment by roddhjav** [comment]
Hi, could you try with the `--debug` option to print more error messages from Tomb?
