### ISSUE TITLE
Timer setting persistent. 

### ISSUE THREAD

**Issue by jpalcantara** [roddhjav/pass-tomb#31]
Hello,

  I installed Pass Tomb and everything is working as advertised except for the timer.  
At one point I decided to invoke the timer to 15 MIN but only for that session and now the timer is called regardless.
This password store will be closed in 15min  and I only entered pass open 
I reboot it and no change.  Did the systemd set this to enable so that it opens tomb with a timer of 15Min? 

Regards,

**Comment by roddhjav** [comment]
Hi, I will need to investigate a bit on it. This feature was known to work (and was fully tested). Since from what I know, systemd-run evolved (and the tests broke). So... I don't know.

**Comment by jpalcantara** [comment]
Understandable, thanks and I will await a feedback.

**Comment by roddhjav** [comment]
That should be fixed now.
