### ISSUE TITLE
An active swap partition is detected...

### ISSUE THREAD

**Issue by creese** [roddhjav/pass-tomb#32]
I have the same issue as https://github.com/roddhjav/pass-tomb/issues/30. Not sure how I should resolve.

I'm running Fedora 34. I have a swap file. I do not have a swap partition. The drive is encrypted. Why do I need to disable swap?

**Comment by roddhjav** [comment]
The swap file itself should be encrypted with a different key than your drive as otherwise any running program could read it. If you don't mind, you can use the `--force` option to bypass the swap check.

**Comment by creese** [comment]
If I want to keep the check, is it possible to encrypt just the swap file, or do I need to a new swap partition?

**Comment by roddhjav** [comment]
Yes it is possible. Have a lot at https://github.com/Whonix/swap-file-creator

**Comment by creese** [comment]
My swap file is a RAM disk. Is the check still meaningful?

**Comment by roddhjav** [comment]
As far I know, yes.

**Comment by roddhjav** [comment]
I don't get it. You have a swap file on RAM?

**Comment by creese** [comment]
Yeah, `swapon` returns `/dev/zram0`. Nothing gets to disk: https://www.phoronix.com/scan.php?page=news_item&px=Fedora-34-zRAM-Tuning.

**Comment by roddhjav** [comment]
Ok, so yes, you might use the force option without security drawback.
