### ISSUE TITLE
Password Store Lost While Attempting to Uninstall

### ISSUE THREAD

**Issue by creese** [roddhjav/pass-tomb#34]
A few days ago, I deleted all the scripts associated with tomb and pass-tomb and disabled the systemd timer while the tomb was open, thinking this was all I needed to do. I also deleted the password tomb. Then I used the system for several days. This morning, when I rebooted, my password store was owned by root (and was empty). What did I do wrong?

**Comment by roddhjav** [comment]
> I also deleted the password tomb. 

The passwords are stored in the password tomb so if you remove it, you lose the password. First, you need to backup the content of the password store while it is open, then you can close the it, remove the password tomb and use the saved password store directory as any normal password repository.
