### ISSUE TITLE
Opening a tomb after closing it doesn't require a password for the gpg key anymore.

### ISSUE THREAD

**Issue by ghost** [roddhjav/pass-tomb#36]
.

**Comment by roddhjav** [comment]
That persistence is handled by the `gpg-agent` you can change its settings to disable it if you really want. However, it can also be handy.

**Comment by gserl** [comment]
I'll just leave this here for anyone else who noticed this and doesn't want the passphrase to be cached for the entire login session. You can insert the line `no-symkey-cache` into your `~/.gnupg/gpg.conf` file. It will force tomb to not cache the decryption passphrase for the symmetric key (aes) it uses to encrypt the tomb. Can also insert the line `no-allow-external-cache` into your `~/.gnupg/gpg-agent.conf` file to force all gpg actions not to use any external (gnome-keyring, etc.) external key-caches often included by default by desktop environments like GNOME, KDE, etc. One other thing, you can alter the `default-cache-ttl` and `max-cache-ttl` values also with lines in `~/.gnupg/gpg-agent.conf` to change how long gpg-agent will cache credentials.
