### ISSUE TITLE
Add a Warning if the pass store is already initialized

### ISSUE THREAD

**Issue by CyanChanges** [roddhjav/pass-tomb#44]
I just `pass tomb`d and my password all gone.
Please add a warning if there is existing files.

**Comment by roddhjav** [comment]
Can you tell me more about what you did. I am not sure I understand how you got the store re-initialized.

**Comment by CyanChanges** [comment]
> Can you tell me more about what you did. I am not sure I understand how you got the store re-initialized.

I just have some pass already there.
And I find this plugin.
I run `pass tomb <my-key-id>`, and enter my passphrase for the key.
And after it completes, i run the `pass` and only a lost-and-found directory there.

**Comment by roddhjav** [comment]
No data has been lost, it is only a mount point. Just close the store: `pass close`, and you will find your normal password store.

**Comment by CyanChanges** [comment]
Thanks

**Comment by CyanChanges** [comment]
hmmm?
i ran `pass close`, and it says `Unable to close the password tomb`
and tried to recreate it, but
![image](https://github.com/user-attachments/assets/92dafe92-6301-492d-bbff-15122e88d602)
