### ISSUE TITLE
Create multiple pass tombs?

### ISSUE THREAD

**Issue by shaform** [roddhjav/pass-tomb#6]
Is it possible to create multiple pass tomb and open them separately or together?

**Comment by roddhjav** [comment]
Yes it is possible, you only need to set the tomb file and key manually using the environment variables. As example:
```sh
# Create, open, close the first tomb as usual
pass tomb <gpgid>
pass open
pass close

# Create a second tomb
PASSWORD_STORE_TOMB_FILE=<tomb_path> PASSWORD_STORE_TOMB_KEY=<key_path> pass tomb <gpgid>

# Open/Close the second tomb
PASSWORD_STORE_TOMB_FILE=<tomb_path> PASSWORD_STORE_TOMB_KEY=<key_path> pass open
```

If you want to open the tomb in a different folder (other than `~/.password-store`), you also need to specify the `PASSWORD_STORE_DIR` variable.

If you always need a second password store, you can create a pass alias, `pass2` that will manage the second store. `.bashrc`:
```sh
alias pass2='PASSWORD_STORE_TOMB_FILE=<tomb_path> PASSWORD_STORE_TOMB_KEY=<key_path> PASSWORD_STORE_DIR=<dir_path> pass'
```

**Comment by shaform** [comment]
Thanks! It's really helpful.
