### ISSUE TITLE
Unable to edit a password entry

### ISSUE THREAD

**Issue by Pawamoy** [roddhjav/pass-tomb#9]
I'm not sure it is related to pass-tomb, but since I used it to create my password store and I can't find an issue tracker for pass, I'm posting this issue in this repo. Maybe @zx2c4 or @jaromil could have an idea on what's going on?

So the issue is that I can't **edit** a password entry. I can show it, copy it in clipboard, etc., but not **edit** it.

Show ok:
```
$ pass show bandyou
****************** (redacted)
```

Update ok (with pass-update extension):
```
$ pass update bandyou
Changing password for bandyou
****************** (redacted)
Are you ready to generate a new password? [y/N] 
```

Edit not ok:
```
$ pass edit bandyou
Error: You must run:
    pass init your-gpg-id
before you may use the password store.

============================================
= pass: the standard unix password manager =
... and the rest of the banner and usage message
```

Edit is not working either with other password entries.

- pass v1.7
- tomb v2.3
- pass-tomb 0.1
- also upgraded to pass-tomb 1.0 and tomb 2.4, still not working

**Comment by Pawamoy** [comment]
I managed to solve this by running `pass init .password-store`. The `pass init` command failed for every key 
```
forum.csdc: reencrypting to 
gpg: .password-store: skipped: No public key
gpg: [stdin]: encryption failed: No public key
```

but now `pass edit` is working again.

I suspect the issue was coming from the fact I'm ignoring the file `.gpg-id` in `.gitignore`. Shouldn't I?
I initialized the git repository afterwards so I wasn't sure what files needed to by tracked or not, I just tracked all the passwords and none of the following:

```
.gpg-id
.host
.last
.tty
.uid
```

**Comment by roddhjav** [comment]
Can you provide the exact commands you did in order to set up your password tomb? Moreover, for `pass-tomb` commands please activate the verbose mode using `-v`.

> Setting a random value in .gpg-id will allow me to show the passwords, and open them for edition in vim, but not save the modifications:

`.gpg-id` should have your GPG key ID, the same you used to generate the password tomb. Otherwise `pass` will never be able to decrypt anything.

**Comment by Pawamoy** [comment]
I guess I did just as explained in the README.

Indeed I put back my GPG ID (I didn't remember I had to put an ID and not a file path), and it is now working again. I don't know what happened exactly but I think the contents of .gpg-id were changed somehow. I'll check that if it happens again, meanwhile I don't think I can do more :/ Thanks for your help!
